/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-secondary-container": "#5d1900",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdbd0",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe6a34",
        "tertiary": "#422d00",
        "surface": "#f8f9fa",
        "outline": "#70787d",
        "primary-fixed-dim": "#95cfe9",
        "on-primary-container": "#84bed8",
        "inverse-primary": "#95cfe9",
        "secondary": "#ab3500",
        "on-surface-variant": "#40484c",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "outline-variant": "#c0c8cc",
        "secondary-fixed-dim": "#ffb59d",
        "on-primary-fixed": "#001f29",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#27657c",
        "tertiary-container": "#5f4200",
        "surface-bright": "#f8f9fa",
        "on-tertiary-container": "#edaa00",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        "primary-container": "#004e64",
        "on-surface": "#191c1d",
        "on-primary-fixed-variant": "#004d63",
        "on-secondary-fixed": "#390c00",
        "surface-container": "#edeeef",
        "tertiary-fixed": "#ffdea9",
        "on-secondary-fixed-variant": "#832600",
        "tertiary-fixed-dim": "#ffba26",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "primary-fixed": "#bce9ff",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed-variant": "#5e4100",
        "on-tertiary-fixed": "#271900",
        "primary": "#003646",
        "background": "#f8f9fa"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}