spring.application.name=explorae-user-service
server.port=${SERVER_PORT:8080}

# Configuracoes de Banco de Dados
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:explorae_db}?sslmode=${DB_SSL_MODE:disable}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes do Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Configuracoes de Log
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

# Configuracoes do Jackson (opcional)
spring.jackson.serialization.indent_output=true

# Configuracoes de Seguranca (JWT)
# Em producao, colocar uma secret mais robusta (maximo 32 caracteres)
jwt.secret=${JWT_SECRET:7a421b7762c2f6d239b6b77242d54e5670851416e8902d689b9d3e8e97f74812}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Tratamento de erro 404 para rotas ausentes (SDGEU-11)
spring.mvc.throw-exception-if-no-handler-found=true 
spring.web.resources.add-mappings=false
